#ifndef SLC_MODULES_ASSEMBLY_GENERATOR_ASSEMBLY_GENERATOR_H
#define SLC_MODULES_ASSEMBLY_GENERATOR_ASSEMBLY_GENERATOR_H

#include "ds/string/string.h"

string *assembly_generator_generate_new_label();

#endif  // SLC_MODULES_ASSEMBLY_GENERATOR_ASSEMBLY_GENERATOR_H